version: '3'
#set outgoing IP address, if hosted on a multi ip host
#sudo iptables -t nat -I POSTROUTING -p all -s 172.31.0.0/16 -j SNAT --to -source xxx.xxx.xxx.xxx
volumes:
  meraki-dkim:
  meraki-vmail:
  meraki-psql:
  meraki-ssl:
  meraki-letsencrypt:
#  meraki-radicale-collections:
  meraki-radicale-rights:

services:
  modoboa:
    #image: meraki/modoboa
    build: .
    #pull_policy: never
    container_name: mail-modoboa
    hostname: mail
    domainname: merakisystems.com
    restart: unless-stopped
    environment:
      TZ: utc
    volumes:
      - meraki-dkim:/var/lib/dkim
      - meraki-vmail:/srv/vmail
      - meraki-psql:/var/lib/postgresql/14/main
      - meraki-ssl:/etc/ssl/
      - meraki-letsencrypt:/etc/letsencrypt/
#      - meraki-radicale-collections:/srv/radicale/collections/
      - meraki-radicale-rights:/etc/radicale/
    #network_mode: "host"

    ports:
      - 80:80
      - 443:443
      - 25:25
      - 587:587
      - 143:143
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    
    networks:
      mail-net:
      
networks:
  mail-net:
    driver: bridge
    # only available in docker 2 
    # enable_ipv6: false
    ipam:
      config:
      - subnet: 172.31.0.0/16
