version: '3'
# set outgoing IP address, if hosted on a multi ip host
# sudo iptables -t nat -I POSTROUTING -p all -s 172.22.0.0/16 -j SNAT --to -source xxx.xxx.xxx.xxx
volumes:
  meraki-dkim:
  meraki-vmail:
  meraki-psql:
  meraki-ssl:

services:
  modoboa:
    image: meraki/modoboa
    build: .
    #pull_policy: never
    container_name: mail-modoboa
    hostname: mail
    domainname: merakisystems.com
    restart: unless-stopped
    environment:
      TZ: utc
    volumes:
      - meraki-dkim:/var/lib/dkim
      - meraki-vmail:/srv/vmail
      - meraki-psql:/var/lib/postgresql/14/main
      - meraki-ssl:/etc/ssl/
      - meraki-letsencrypt:/etc/letsencrypt/
    #network_mode: "host"

    ports:
      - 80:80
      - 443:443
      - 25:25
      - 587:587
      - 143:143
