version: '3'
#set outgoing IP address, if hosted on a multi ip host
#sudo iptables -t nat -I POSTROUTING -p all -s 172.31.0.0/16 -j SNAT --to -source xxx.xxx.xxx.xxx
name: ${DOMAIN}-mail
volumes:
  dkim:
  vmail:
  psql:
  ssl:
  letsencrypt:
  radicale-collections:
  radicale-rights:

services:
  modoboa:
    #image: meraki/modoboa
    build: .
    #pull_policy: never
    container_name: ${DOMAIN}-mail-modoboa
    hostname: mail
    domainname: ${DOMAIN}
    restart: unless-stopped
    environment:
      TZ: utc
      DOMAIN: ${DOMAIN}
    volumes:
      - dkim:/var/lib/dkim
      - vmail:/srv/vmail
      - psql:/var/lib/postgresql/14/main
      - ssl:/etc/ssl/
      - letsencrypt:/etc/letsencrypt/
      - radicale-collections:/srv/radicale/
      - radicale-rights:/etc/radicale/
    #network_mode: "host"

    ports:
      - 80:80
      - 443:443
      - 25:25
      - 587:587
      - 143:143
#      - 19999:19999
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    
    networks:
      mail-net:
      
networks:
  mail-net:
    driver: bridge
    # only available in docker 2 
    # enable_ipv6: false
    ipam:
      config:
      - subnet: 172.31.0.0/16
